### ISSUE TITLE
您好，关于代码和论文的事情想和您询问下

### ISSUE THREAD

**Issue by Yuri-delta** [XinghuaMa/TR-Net#1]
您好，我在网上看到了关于您工作的视频，令人大受鼓舞，您的工作太精彩了！但我在网上目前还没能搜索到您这项工作的文章，想要问您能否私下发给我下关于您工作的文章，我的邮箱是bylll12138@163.com，十分感谢您！
另外想和您确认下代码是否会开源以及开源的时间，十分期待您的工作！

**Comment by lydials** [comment]
@Yuri-delta 你好，请问视频地址能分享一下吗？

**Comment by Yuri-delta** [comment]
> @Yuri-delta 你好，请问视频地址能分享一下吗？

https://www.bilibili.com/video/BV1Uo4y1k78X?p=1&share_medium=android&share_plat=android&share_source=WEIXIN&share_tag=s_i&timestamp=1624876130&unique_k=XcJ3M7

**Comment by luogongning** [comment]
> 您好，我在网上看到了关于您工作的视频，令人大受鼓舞，您的工作太精彩了！但我在网上目前还没能搜索到您这项工作的文章，想要问您能否私下发给我下关于您工作的文章，我的邮箱是[bylll12138@163.com](mailto:bylll12138@163.com)，十分感谢您！
> 另外想和您确认下代码是否会开源以及开源的时间，十分期待您的工作！

感谢支持，文章已经发布在arxiv上了!

**Comment by Yuri-delta** [comment]
万分感谢！



在 2021-07-23 08:35:34，"Gongning Luo" ***@***.***> 写道：

***@***.***，十分感谢您！
另外想和您确认下代码是否会开源以及开源的时间，十分期待您的工作！

感谢支持，文章已经发布在arxiv上了!
